FROM almalinux:9
ENV course="DEVOPS WITH AWS"\
trainer="SIVAKUMAR REDDY"\
duration="120HS"
ARG USERNAME="SIVAKUMAR REDDY"
#ARG USERNAME= ${trainer} we cannot access environment variable in build
RUN echo "Hello user: ${USERNAME}" > /tmp/devops.txt
CMD ["sleep", "100"]
 
